# MKSHELL - Sets the shell that mk uses (see mk(1))
# NAME - The name of the source folder
# URL  - URL of the repository
# DEST - Destination to install the packages. Point it at /
# MAN  - Location of the manual pages. Point it at $DEST/share/man
# *FLAGS - Extra flags to pass to the program. Must contain -static
# CC   - The C compiler to execute

MKSHELL=/bin/sh
NAME=ncurses
URL=https://github.com/mirror/ncurses.git
CC=musl-gcc
DEST=${INSTDEST}
MAN=${MANDEST}
CFLAGS=-static
LDFLAGS=-static

update:V:
	if [[ ! -d $NAME ]]; then git clone $URL; fi
	git -C $NAME pull
	(cd $NAME && ./configure --prefix="" \
	 CC=$CC CFLAGS=$CFLAGS LDFLAGS=$LDFLAGS \
	 DESTDIR=$DEST)

build:V:
	make -C $NAME build

install:V:
	DESTDIR=$DEST make -C $NAME install

uninstall:V:
	DESTDIR=$DEST make -C $NAME uninstall

clean:V:
	rm -rf $NAME

do:V: update build install
