# MKSHELL - Sets the shell that mk uses (see mk(1))
# NAME - The name of the source folder
# URL  - URL of the repository
# DEST - Destination to install the packages. Point it at /
# MAN  - Location of the manual pages. Point it at $DEST/share/man
# FLAGS - Extra flags to pass to the program

MKSHELL=/bin/sh
NAME=tcc
URL=http://repo.or.cz/tinycc.git
DEST=${INSTDEST}
MAN=${MANDEST}
FLAGS=

update:V:
	if [[ ! -d $NAME ]]; then git clone $URL tcc; fi
	git -C $NAME pull

install:V:
	cd $NAME && ./configure --prefix=$DEST \
				--exec-prefix=$DEST \
				--sharedir=$DEST/share \
				--mandir=$DEST$MAN
	make -C $NAME install

uninstall:V:
	make -C $NAME uninstall

clean:V:
	rm -rf $NAME

do:V: update install
