# MKSHELL - Sets the shell that mk uses (see mk(1))
# NAME - The name of the source folder
# URL  - URL of the repository
# DEST - Destination to install the packages. Point it at /
# MAN  - Location of the manual pages. Point it at $DEST/share/man
# *FLAGS - Extra flags to pass to the program. Must contain -static

MKSHELL=/bin/sh
NAME=sbase
URL=git://git.suckless.org/sbase
DEST=${INSTDEST}
MAN=${MANDEST}
CFLAGS=-static
LDFLAGS=-static

update:V:
	if [[ ! -d $NAME ]]; then git clone $URL; fi
	git -C $NAME pull
	sed -i 's|^MANPREFIX\s*=.*$|MANPREFIX = '$MAN'|' $NAME/config.mk
	sed -i -e 's/^PREFIX\s*=.*$/PREFIX = /' $NAME/config.mk
	# TODO: There is a bug that if you update then it will add duplicates to the CFLAGS.
	sed -i -e 's/^CFLAGS\s*= \(.*\)$/CFLAGS = \1 '$CFLAGS'/' $NAME/config.mk
	sed -i -e 's/^LDFLAGS\s*= \(.*\)$/LDFLAGS = \1 '$LDFLAGS'/' $NAME/config.mk

build:V:
	make -C $NAME

install:V:
	DESTDIR=$DEST make -C $NAME install

uninstall:V:
	DESTDIR=$DEST make -C $NAME uninstall

clean:V:
	rm -rf $NAME

do:V: update build install
