# MKSHELL - Sets the shell that mk uses (see mk(1))
# NAME - The name of the source folder
# URL  - URL of the repository
# DEST - Destination to install the packages. Point it at /
# MAN  - Location of the manual pages. Point it at $DEST/share/man
# ARCH - See 9base/config.mk for available options.
# FLAGS - Extra flags to pass to the program

MKSHELL=/bin/sh
NAME=9base
URL=git://git.suckless.org/9base
DEST=${INSTDEST}
MAN=${MANDEST}
ARCH=x86_64
FLAGS=

update:V:
	if [[ ! -d $NAME ]]; then git clone $URL; fi
	git -C $NAME pull
	sed -i "s/^PREFIX\s*=.*/PREFIX =/" $NAME/config.mk
	sed -i "s|^MANPREFIX\s*=.*|MANPREFIX = "$MAN"|" $NAME/config.mk
	sed -i "s|^OBJTYPE\s*=.*|OBJTYPE = "$ARCH"|" $NAME/config.mk

install:V:
	DESTDIR=$DEST make -C $NAME install

uninstall:V:
	DESTDIR=$DEST make -C $NAME uninstall

clean:V:
	rm -rf $NAME

do:V: update install
