# MKSHELL - Sets the shell that mk uses (see mk(1))
# NAME - The name of the source folder
# URL  - URL of the repository
# DEST - Destination to install the packages. Point it at /
# MAN  - Location of the manual pages. Point it at $DEST/share/man
# *FLAGS - Extra flags to pass to the program. Remove from them at your peril.

MKSHELL=/bin/sh
NAME=bsdcurses
URL=https://github.com/sabotage-linux/netbsd-curses.git
DEST=${INSTDEST}
MAN=${MANDEST}
CFLAGS=-I./libcurses
LDFLAGS=-static

update:V:
	if [[ ! -d $NAME ]]; then git clone $URL $NAME; fi
	git -C $NAME pull
	sed -i -e 's/^PREFIX\s*=.*$/PREFIX =/' $NAME/GNUmakefile
	sed -i -e 's|^CFLAGS+=\(.*\)$|CFLAGS+= \1 '$CFLAGS'|' $NAME/GNUmakefile

build:V:
	make -C $NAME LDFLAGS=$FLAGS

install:V:
	make -C $NAME install DESTDIR=$DEST

uninstall:V:
	make -C $NAME uninstall DESTDIR=$DEST

clean:V:
	rm -rf $NAME

do:V: update build install
