# MKSHELL - Sets the shell that mk uses (see mk(1))
# NAME - The name of the source folder
# URL  - URL of the repository
# DEST - Destination to install the packages. Point it at /
# MAN  - Location of the manual pages. Point it at $DEST/share/man
# FLAGS - Extra flags to pass to the program

MKSHELL=/bin/bash
NAME=ubase
URL=git://git.suckless.org/ubase
DEST=${INSTDEST}
MAN=${MANDEST}
FLAGS=-static

update:V:
	if [[ ! -d $NAME ]]; then git clone $URL; fi
	git -C $NAME pull
	MAN=$MAN sed -i 's|^MANPREFIX = .*|MANPREFIX = '$MAN'|' $NAME/config.mk
	sed -i -e 's/^PREFIX = .*/PREFIX = /' $NAME/config.mk

install:V:
	DESTDIR=$DEST CFLAGS=$FLAGS make -C $NAME install

uninstall:V:
	DESTDIR=$DEST make -e -C $NAME uninstall

clean:V:
	rm -rf $NAME

do:V: update install
